/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#40ceed",
        "error-dim": "#d73357",
        "on-primary-container": "#2b006e",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "surface": "#060e20",
        "on-primary-fixed-variant": "#370086",
        "on-surface": "#dee5ff",
        "on-background": "#dee5ff",
        "primary-fixed": "#ae8dff",
        "inverse-surface": "#faf8ff",
        "surface-bright": "#1f2b49",
        "on-secondary-fixed-variant": "#005969",
        "secondary": "#53ddfc",
        "on-tertiary": "#471a00",
        "tertiary-fixed": "#ff955a",
        "outline-variant": "#40485d",
        "surface-tint": "#ba9eff",
        "on-primary": "#39008c",
        "on-secondary-fixed": "#003a45",
        "on-tertiary-container": "#321000",
        "on-surface-variant": "#a3aac4",
        "tertiary-fixed-dim": "#ff7f2f",
        "background": "#060e20",
        "surface-container-high": "#141f38",
        "tertiary-container": "#f77113",
        "tertiary": "#ff8439",
        "error-container": "#a70138",
        "primary-dim": "#8455ef",
        "surface-variant": "#192540",
        "surface-container": "#0f1930",
        "secondary-fixed": "#65e1ff",
        "inverse-on-surface": "#4d556b",
        "on-secondary-container": "#ecfaff",
        "outline": "#6d758c",
        "surface-container-low": "#091328",
        "tertiary-dim": "#fd761a",
        "on-secondary": "#004b58",
        "secondary-fixed-dim": "#48d4f3",
        "on-tertiary-fixed": "#2e0e00",
        "primary-fixed-dim": "#a27cff",
        "inverse-primary": "#6e3bd7",
        "surface-container-lowest": "#000000",
        "primary-container": "#ae8dff",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#632800",
        "secondary-container": "#00687a",
        "error": "#ff6e84",
        "surface-container-highest": "#192540",
        "surface-dim": "#060e20",
        "primary": "#ba9eff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        }
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
